a_private_f = "tests/Alice_private_key"
a_public_f = "tests/Alice_public_key"
b_private_f = "tests/Bob_private_key"
b_public_f = "tests/Bob_public_key"
a_pgps_f = "tests/Alice_pgps"
b_pgps_f = "tests/Bob_pgps"
